<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Maheshs-MacBook-Pro.local" failures="3" tests="4" name="Tests" time="24.01" errors="0" timestamp="2021-07-24T10:59:37 IST">
  <testcase classname="ttt.bootcamp.testcases.LoginPageTest" name="validDataLogin" time="5.258">
    <failure type="java.lang.AssertionError" message="User is not able to login. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User is not able to login. expected [true] but found [false]
at ttt.bootcamp.testcases.LoginPageTest.validDataLogin(LoginPageTest.java:15)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- validDataLogin -->
  <testcase classname="ttt.bootcamp.testcases.LoginPageTest" name="invalidDataLogin" time="5.276"/>
  <testcase classname="ttt.bootcamp.testcases.LoginPageTest" name="validDataLogin" time="4.614">
    <failure type="java.lang.AssertionError" message="User is not able to login. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User is not able to login. expected [true] but found [false]
at ttt.bootcamp.testcases.LoginPageTest.validDataLogin(LoginPageTest.java:15)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- validDataLogin -->
  <testcase classname="ttt.bootcamp.testcases.LoginPageTest" name="validDataLogin" time="4.48">
    <failure type="java.lang.AssertionError" message="User is not able to login. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User is not able to login. expected [true] but found [false]
at ttt.bootcamp.testcases.LoginPageTest.validDataLogin(LoginPageTest.java:15)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- validDataLogin -->
</testsuite> <!-- Tests -->
